{
 "title": "Pipelines Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Job 0",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pipeline_job_status{job_name=\"job-0\"}",
     "legendFormat": "{{ job_name }}"
    }
   ]
  },
  {
   "title": "Job 1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pipeline_job_status{job_name=\"job-1\"}",
     "legendFormat": "{{ job_name }}"
    }
   ]
  },
  {
   "title": "Job 2",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pipeline_job_status{job_name=\"job-2\"}",
     "legendFormat": "{{ job_name }}"
    }
   ]
  },
  {
   "title": "Job 3",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pipeline_job_status{job_name=\"job-3\"}",
     "legendFormat": "{{ job_name }}"
    }
   ]
  },
  {
   "title": "Job 4",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pipeline_job_status{job_name=\"job-4\"}",
     "legendFormat": "{{ job_name }}"
    }
   ]
  },
  {
   "title": "Total Bytes Processed Through Pipeline",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "format": "decmbytes",
   "valueName": "total",
   "targets": [
    { "expr": "pipeline_processed_bytes_total", "legendFormat": "bytes" }
   ]
  },
  {
   "title": "Total Records Imported",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "pipeline_imported_records_total",
     "legendFormat": "records"
    }
   ]
  },
  {
   "title": "Imported Records",
   "type": "graph",
   "description": "Amount of records each job  has successfully imported",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pipeline_imported_records", "legendFormat": "{{ job_name }}" }
   ]
  },
  {
   "title": "Exceptions",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    { "expr": "pipeline_exceptions_raised", "legendFormat": "{{ job_name }}" }
   ]
  },
  {
   "title": "Average Processing Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "expr": "pipeline_job_seconds", "legendFormat": "{{ job_name }}" }
   ]
  },
  {
   "title": "Bytes Processed",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    { "expr": "pipeline_bytes_processed", "legendFormat": "{{ job_name }}" }
   ]
  }
 ]
}